;;; pyim-wbdict-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from pyim-wbdict.el

(autoload 'pyim-wbdict-v86-enable "pyim-wbdict" "\
Add wubi dict (86 version) to pyim." t)
(autoload 'pyim-wbdict-v86-single-enable "pyim-wbdict" "\
Add wubi dict (86 version, single character) to pyim." t)
(autoload 'pyim-wbdict-v98-enable "pyim-wbdict" "\
Add wubi dict (98 version) to pyim." t)
(autoload 'pyim-wbdict-v98-morphe-enable "pyim-wbdict" "\
Add wubi dict (98 version with superset & single-word) to pyim." t)

;;; End of scraped data

(provide 'pyim-wbdict-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8-emacs-unix
;; End:

;;; pyim-wbdict-autoloads.el ends here
