;;; init-theme.el --- Theme presets for this config -*- lexical-binding: t; -*-

;;; Commentary:

;;; Code:

(defvar my/theme-preset 'gits
  "Theme preset applied to GUI frames.")

(defconst my/modus-themes-directory
  (expand-file-name "themes" data-directory)
  "Directory containing the built-in Modus theme libraries.")

(defvar my/theme-refresh-suppressed nil
  "Non-nil while theme changes should not trigger expensive dependent refreshes.")

(defconst my/gits-modus-palette
  '((accent-0 "#00e5ff")
    (accent-1 "#ff0044")
    (bg-active bg-main)
    (bg-added "#0a2018")
    (bg-added-refine "#143a22")
    (bg-changed "#0a1e38")
    (bg-changed-refine "#142840")
    (bg-completion "#0a1a2a")
    (bg-completion-match-0 "#050810")
    (bg-completion-match-1 "#050810")
    (bg-completion-match-2 "#050810")
    (bg-completion-match-3 "#050810")
    (bg-hl-line "#0d1e2e")
    (bg-hover-secondary "#0d2030")
    (bg-line-number-active unspecified)
    (bg-line-number-inactive "#050810")
    (bg-main "#050810")
    (bg-mark-delete "#2a0a14")
    (bg-mark-select "#0a1e38")
    (bg-mode-line-active "#0a1628")
    (bg-mode-line-inactive "#080c16")
    (bg-prominent-err "#2a0a14")
    (bg-prompt unspecified)
    (bg-prose-block-contents "#0d1628")
    (bg-prose-block-delimiter bg-prose-block-contents)
    (bg-region "#0d2840")
    (bg-removed "#2a0a14")
    (bg-removed-refine "#3a1020")
    (bg-tab-bar "#050810")
    (bg-tab-current "#080c16")
    (bg-tab-other "#050810")
    (border-mode-line-active nil)
    (border-mode-line-inactive nil)
    (builtin "#00e5ff")
    (comment "#2d5a70")
    (constant "#ff4466")
    (cursor "#00e5ff")
    (date-weekday "#00e5ff")
    (date-weekend "#ffaa00")
    (docstring "#4a7a8a")
    (err "#ff0044")
    (fg-active fg-main)
    (fg-completion "#8ecede")
    (fg-completion-match-0 "#00e5ff")
    (fg-completion-match-1 "#ff0044")
    (fg-completion-match-2 "#00cc77")
    (fg-completion-match-3 "#ffaa00")
    (fg-heading-0 "#ff0044")
    (fg-heading-1 "#ff4466")
    (fg-heading-2 "#ffaa00")
    (fg-heading-3 "#00cc77")
    (fg-heading-4 "#00e5ff")
    (fg-line-number-active "#00e5ff")
    (fg-line-number-inactive "#1a3a50")
    (fg-link "#00e5ff")
    (fg-main "#68b8cc")
    (fg-mark-delete "#ff0044")
    (fg-mark-select "#00e5ff")
    (fg-mode-line-active "#8ecede")
    (fg-mode-line-inactive "#2a4a5a")
    (fg-prominent-err "#ff0044")
    (fg-prompt "#cc55ff")
    (fg-prose-block-delimiter "#1a3a50")
    (fg-prose-verbatim "#00cc77")
    (fg-region "#8ecede")
    (fnname "#00c5dd")
    (fringe "#050810")
    (identifier "#cc55ff")
    (info "#00cc77")
    (keyword "#cc55ff")
    (name "#00e5ff")
    (number "#ffaa00")
    (property "#00b8cc")
    (string "#00cc77")
    (type "#ffaa00")
    (variable "#ff8800")
    (warning "#ffaa00"))
  "Palette overrides used by the emacs-solo GITS theme preset.")

(defconst my/matrix-modus-palette
  '((accent-0 "#00ff41")
    (accent-1 "#008f11")
    (bg-active bg-main)
    (bg-added "#003b00")
    (bg-added-refine "#005a00")
    (bg-changed "#004800")
    (bg-changed-refine "#006600")
    (bg-completion "#0d0208")
    (bg-completion-match-0 "#0d0208")
    (bg-completion-match-1 "#0d0208")
    (bg-completion-match-2 "#0d0208")
    (bg-completion-match-3 "#0d0208")
    (bg-hl-line "#002200")
    (bg-hover-secondary "#003b00")
    (bg-line-number-active unspecified)
    (bg-line-number-inactive "#0d0208")
    (bg-main "#0d0208")
    (bg-mark-delete "#190a10")
    (bg-mark-select "#003b00")
    (bg-mode-line-active "#001900")
    (bg-mode-line-inactive "#001900")
    (bg-prominent-err "#190a10")
    (bg-prompt unspecified)
    (bg-prose-block-contents "#001600")
    (bg-prose-block-delimiter bg-prose-block-contents)
    (bg-region "#003b00")
    (bg-removed "#190a10")
    (bg-removed-refine "#2b1520")
    (bg-tab-bar "#001900")
    (bg-tab-current bg-main)
    (bg-tab-other "#001900")
    (border-mode-line-active nil)
    (border-mode-line-inactive nil)
    (builtin "#00ff41")
    (comment "#005a00")
    (constant "#00ff41")
    (cursor "#00ff41")
    (date-weekday "#00ff41")
    (date-weekend "#008f11")
    (docstring "#00c738")
    (err "#00ff71")
    (fg-active fg-main)
    (fg-completion "#00ff41")
    (fg-completion-match-0 "#00ff41")
    (fg-completion-match-1 "#00ff71")
    (fg-completion-match-2 "#00c738")
    (fg-completion-match-3 "#008f11")
    (fg-heading-0 "#00ff41")
    (fg-heading-1 "#00c738")
    (fg-heading-2 "#00a52a")
    (fg-heading-3 "#008f11")
    (fg-heading-4 "#005a00")
    (fg-line-number-active "#00ff41")
    (fg-line-number-inactive "#006600")
    (fg-link "#00ff41")
    (fg-main "#00ff41")
    (fg-mark-delete "#00ff71")
    (fg-mark-select "#00ff41")
    (fg-mode-line-active "#00c738")
    (fg-mode-line-inactive "#005a00")
    (fg-prominent-err "#00ff71")
    (fg-prompt "#00ff41")
    (fg-prose-block-delimiter "#006600")
    (fg-prose-verbatim "#00c738")
    (fg-region "#00ff41")
    (fnname "#00ff41")
    (fnname-call "#00ff41")
    (fringe "#0d0208")
    (identifier "#00c738")
    (info "#00ff41")
    (keyword "#00c738")
    (name "#00ff41")
    (number "#008f11")
    (preprocessor "#00c738")
    (property "#00ff41")
    (string "#00c738")
    (type "#00a52a")
    (variable "#008f11")
    (variable-use "#00ff41")
    (warning "#00a52a"))
  "Palette overrides used by the emacs-solo Matrix theme preset.")

(defun my/ensure-modus-themes ()
  "Load the Modus theme support library from the built-in themes directory."
  (add-to-list 'load-path my/modus-themes-directory)
  (add-to-list 'custom-theme-load-path my/modus-themes-directory)
  (require 'modus-themes))

(defun my/disable-active-themes ()
  "Disable all currently active custom themes."
  (mapc #'disable-theme custom-enabled-themes))

(defun my/run-theme-dependent-refresh ()
  "Refresh theme-dependent UI components once after theme changes settle."
  (when (fboundp 'segment-line-refresh-faces)
    (segment-line-refresh-faces))
  (when (fboundp 'my/flymake-refresh-fancy-theme)
    (my/flymake-refresh-fancy-theme)))

(defun my/apply-gits-theme-faces ()
  "Apply the extra face overrides used by the emacs-solo GITS preset."
  (custom-theme-set-faces
   'user
   '(change-log-acknowledgment ((t (:foreground "#00e5ff"))))
   '(change-log-date ((t (:foreground "#00cc77"))))
   '(change-log-name ((t (:foreground "#ffaa00"))))
   '(diff-context ((t (:foreground "#1a3a50"))))
   '(diff-file-header ((t (:foreground "#ff4466"))))
   '(diff-header ((t (:foreground "#00e5ff"))))
   '(diff-hunk-header ((t (:foreground "#ffaa00"))))
   '(gnus-button ((t (:foreground "#00e5ff"))))
   '(gnus-group-mail-3 ((t (:foreground "#00e5ff"))))
   '(gnus-group-mail-3-empty ((t (:foreground "#00e5ff"))))
   '(gnus-header-content ((t (:foreground "#68b8cc"))))
   '(gnus-header-from ((t (:foreground "#cc55ff"))))
   '(gnus-header-name ((t (:foreground "#00cc77"))))
   '(gnus-header-subject ((t (:foreground "#00e5ff"))))
   '(log-view-message ((t (:foreground "#00e5ff"))))
   '(match ((t (:background "#0d2840" :foreground "#8ecede"))))
   '(modus-themes-search-current ((t (:background "#ff0044" :foreground "#050810"))))
   '(modus-themes-search-lazy ((t (:background "#0d2840" :foreground "#8ecede"))))
   '(newsticker-extra-face ((t (:foreground "#1a3a50" :height 0.8 :slant italic))))
   '(newsticker-feed-face ((t (:foreground "#ff0044" :height 1.2 :weight bold))))
   '(newsticker-treeview-face ((t (:foreground "#68b8cc"))))
   '(newsticker-treeview-selection-face ((t (:background "#0d2840" :foreground "#8ecede"))))
   '(tab-bar ((t (:background "#050810" :foreground "#2a4a5a"))))
   '(tab-bar-tab ((t (:background "#080c16" :underline nil))))
   '(tab-bar-tab-inactive ((t (:background "#050810" :foreground "#1a3a50"))))
   '(tab-bar-tab-group-current ((t (:background "#080c16" :foreground "#68b8cc" :underline t))))
   '(tab-bar-tab-group-inactive ((t (:background "#050810" :foreground "#2a4a5a"))))
   '(vc-dir-file ((t (:foreground "#00e5ff"))))
   '(vc-dir-header-value ((t (:foreground "#68b8cc"))))))

(defun my/apply-gits-theme ()
  "Apply the emacs-solo GITS theme preset."
  (my/ensure-modus-themes)
  (setq modus-themes-italic-constructs t
        modus-themes-bold-constructs t
        modus-themes-mixed-fonts nil
        modus-themes-prompts '(bold intense)
        modus-themes-common-palette-overrides my/gits-modus-palette)
  (my/disable-active-themes)
  (load-theme 'modus-vivendi t)
  (my/apply-gits-theme-faces))

(defun my/apply-matrix-theme-faces ()
  "Apply the extra face overrides used by the emacs-solo Matrix preset."
  (custom-theme-set-faces
   'user
   '(change-log-acknowledgment ((t (:foreground "#00c738"))))
   '(change-log-date ((t (:foreground "#008f11"))))
   '(change-log-name ((t (:foreground "#00a52a"))))
   '(diff-context ((t (:foreground "#00ff41"))))
   '(diff-file-header ((t (:foreground "#00c738"))))
   '(diff-header ((t (:foreground "#00ff41"))))
   '(diff-hunk-header ((t (:foreground "#008f11"))))
   '(flymake-warning ((t (:foreground "#00a52a"
                                      :underline (:color "#00a52a" :style wave)))))
   '(flymake-note ((t (:foreground "#00ff41"
                                   :underline (:color "#00ff41" :style wave)))))
   '(link ((t (:foreground "#00ff41"
                           :underline (:color "#00ff41" :style line)))))
   '(gnus-button ((t (:foreground "#00ff41"))))
   '(gnus-group-mail-3 ((t (:foreground "#00ff41"))))
   '(gnus-group-mail-3-empty ((t (:foreground "#00ff41"))))
   '(gnus-header-content ((t (:foreground "#00c738"))))
   '(gnus-header-from ((t (:foreground "#008f11"))))
   '(gnus-header-name ((t (:foreground "#00c738"))))
   '(gnus-header-subject ((t (:foreground "#00ff41"))))
   '(log-view-message ((t (:foreground "#00c738"))))
   '(match ((t (:background "#003b00" :foreground "#00ff41"))))
   '(modus-themes-search-current ((t (:background "#00ff41" :foreground "#0d0208"))))
   '(modus-themes-search-lazy ((t (:background "#003b00" :foreground "#00ff41"))))
   '(newsticker-extra-face ((t (:foreground "#005a00" :height 0.8 :slant italic))))
   '(newsticker-feed-face ((t (:foreground "#00a52a" :height 1.2 :weight bold))))
   '(newsticker-treeview-face ((t (:foreground "#00ff41"))))
   '(newsticker-treeview-selection-face ((t (:background "#003b00" :foreground "#00ff41"))))
   '(tab-bar ((t (:background "#001900" :foreground "#00c738"))))
   '(tab-bar-tab ((t (:background "#0d0208"))))
   '(tab-bar-tab-group-current ((t (:background "#0d0208" :foreground "#00c738"))))
   '(tab-bar-tab-group-inactive ((t (:background "#0d0208" :foreground "#005a00"))))
   '(tab-bar-tab-inactive ((t (:background "#0d0208" :foreground "#008f11"))))
   '(vc-dir-file ((t (:foreground "#00ff41"))))
   '(vc-dir-header-value ((t (:foreground "#00c738"))))))

(defun my/apply-matrix-theme ()
  "Apply the emacs-solo Matrix theme preset."
  (my/ensure-modus-themes)
  (setq modus-themes-italic-constructs t
        modus-themes-bold-constructs t
        modus-themes-mixed-fonts nil
        modus-themes-prompts '(bold intense)
        modus-themes-common-palette-overrides my/matrix-modus-palette)
  (my/disable-active-themes)
  (load-theme 'modus-vivendi t)
  (my/apply-matrix-theme-faces))

(defun my/apply-theme-preset (theme-preset &optional defer-refresh)
  "Apply THEME-PRESET to the current frame set.
When DEFER-REFRESH is non-nil, skip the final dependent UI refresh."
  (let ((my/theme-refresh-suppressed t))
    (pcase theme-preset
      ('gits
       (my/apply-gits-theme))
      ('matrix
       (my/apply-matrix-theme))
      ((pred symbolp)
       (my/disable-active-themes)
       (load-theme theme-preset t))
      (_ nil)))
  (unless defer-refresh
    (my/run-theme-dependent-refresh)))

(provide 'init-theme)
;;; init-theme.el ends here.
